{
 "title": "APP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "500",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{status=\"500\"}"
    }
   ]
  },
  {
   "title": "400",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{status=\"400\"}"
    }
   ]
  },
  {
   "title": "requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    }
   ]
  }
 ]
}